apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-kafka
  namespace: observability
  labels:
    app.kubernetes.io/name: strimzi-kafka
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      interval: 15s

