apiVersion: v1
kind: Namespace
metadata:
  name: risk-assistant
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: risk-assistant
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/part-of: messaging
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    app.kubernetes.io/part-of: cicd
