apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: risk-assistant-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git://host.minikube.internal/risk-assistant.git
    targetRevision: HEAD
    path: infra/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
